sonar.projectKey=abelserradev_frontend_gastosmobile
sonar.organization=abelserradev
sonar.projectName=gastos-frontend
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/android/**,**/*.spec.ts
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/web/lcov.info
sonar.sourceEncoding=UTF-8
